### ISSUE TITLE
web page issue

### ISSUE THREAD

**Issue by ddobrinskiy** [ReviewNB/support#56] opened 2020-04-10 12:26 UTC
Hi, when reviewing a PR, the arrow is displayed as text, which is perplexing.

I'm running firefox 75.0 on linux

![](https://i.imgur.com/HLk32Xc.png)

**Comment by amit1rrr** [comment] 2020-04-10 12:56
I updated Firefox on my Mac to 75.0 and can't seem to reproduce this. The HTML is exactly the same 
as you and it renders fine (see screenshot below). One thing I would like to verify are the properties of `material-icons` css class. Can you click on that  <i> tag in the inspector window and scroll to `material-icons` properties as I have highlighted in my screenshot.

Sorry to bother you with requests but I will need your help to debug since I don't have a way to reproduce this.

![Screenshot 2020-04-10 at 6 22 54 PM](https://user-images.githubusercontent.com/1350490/78992326-9a0b6d00-7b58-11ea-974d-6d6d77dcdabe.png)

**Comment by amit1rrr** [comment] 2020-04-21 12:28
Closing due to lack of information or ability to reproduce. Fee free to reopen with additional information.

**Closed by amit1rrr** 2020-04-21 12:28 UTC
