### ISSUE TITLE
LaTeX rendering ignores escaped dollar signs

### ISSUE THREAD

**Issue by sid-kap** [ReviewNB/support#41] opened 2019-09-06 22:59 UTC
Including `\$` in a Markdown cell should escape the dollar sign and prevent Latex from being rendered. Instead, latex is being rendered regardless, so a lot of random text appears as latex when it should not

**Comment by amit1rrr** [comment] 2019-09-07 05:42
@sid-kap Thanks for reporting.

I reproduced this issue below and it's indeed a problem. We'll deploy a fix for this next week. Looks like you are from Affirm Inc who are using on-prem version of ReviewNB. So I'll also create an update for you to pick up as well.

Actual change in Notebook - 

<img width="851" alt="Screenshot 2019-09-07 at 11 07 21 AM" src="https://user-images.githubusercontent.com/1350490/64470402-3d7a4680-d160-11e9-8f00-af9bf2b0b31d.png">

Our diff screwed it up -
<img width="1206" alt="Screenshot 2019-09-07 at 11 07 10 AM" src="https://user-images.githubusercontent.com/1350490/64470405-49660880-d160-11e9-9882-e76198b94af7.png">

**Comment by amit1rrr** [comment] 2019-09-09 12:57
@sid-kap The fix is deployed on app.reviewnb.com

Going to close this issue now. I will inform you once we push out an on-prem update to be picked up by Affirm's technical team. Thanks again for reporting the issue.



![Screenshot 2019-09-09 at 6 23 05 PM](https://user-images.githubusercontent.com/1350490/64532374-f7bfa880-d32e-11e9-9c9b-a6a5055f9a77.png)

**Closed by amit1rrr** 2019-09-09 12:57 UTC

**Comment by sid-kap** [comment] 2019-09-09 23:56
Thanks for addressing this so quickly!

**Comment by amit1rrr** [comment] 2019-09-10 14:15
@sid-kap You're welcome. We also just pushed an update to Affirm's on-prem version and have notified your technical team for update. Matt Leonard is our point of contact if you wish to know when the fix would be rolled out to you.

Also, I'd love to get your feedback on ReviewNB usage and some upcoming features. If you'd like to opt into some friendly feedback, please write to me at amit@reviewnb.com. Thank you.

**Comment by sid-kap** [comment] 2019-09-11 21:43
Sure! I've only been using ReviewNB for a week or so, but I have some ideas/feature requests that I could write up and send you when I get the time
