### ISSUE TITLE
Bug: Only one comment possible in review

### ISSUE THREAD

**Issue by anneadb** [ReviewNB/support#62] opened 2020-06-22 14:15 UTC
Hi,

I am currently testing ReviewNB to see if it is useful for my team at work and came across the following error: 

After leaving a comment on a code block in a pull request and starting a review I can no longer keep scrolling. So the only thing I can do is either "finish" or "discard" the review which I usually do not want to do after just one comment.

This is happening in both Chrome and Safari.

Best, Anne

**Comment by amit1rrr** [comment] 2020-06-22 14:54
@anneadb Sorry about that. Looks like it's a side effect of a recent code change on the site. Give me some time to check the root cause, I will keep you posted. Sorry for the inconvenience.

**Comment by amit1rrr** [comment] 2020-06-22 15:14
We have reverted our recent deployment. So you should be able to scroll properly now. We'll release our new changes later with the proper fix. 

Please note, you'll need to do a hard refresh once (Cmd+R) to get the latest version.

Closing, feel free to open if you see any more issues.

**Closed by amit1rrr** 2020-06-22 15:14 UTC

**Comment by amit1rrr** [comment] 2020-06-23 06:13
Quick update - we've fixed the root cause for scrolling freeze & deployed the new changes back online.
